# Generated by Django 3.1.7 on 2021-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroidApi', '0002_auto_20210309_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=60)),
                ('periodStart', models.IntegerField(max_length=10)),
                ('periodEnd', models.IntegerField(max_length=10)),
                ('possibleImpacts', models.IntegerField(max_length=10)),
                ('cumulativeImpactProbability', models.IntegerField(max_length=10)),
                ('asteroidVelocity', models.IntegerField(max_length=10)),
                ('absoluteMagnitude', models.IntegerField(max_length=10)),
                ('cumulativePalermoScale', models.IntegerField(max_length=10)),
                ('maximumPalermoScale', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orbits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('epoch', models.IntegerField(max_length=10)),
                ('orbitAxis', models.IntegerField(max_length=10)),
                ('orbitEccentricity', models.IntegerField(max_length=10)),
                ('orbitInclanation', models.IntegerField(max_length=10)),
                ('periphelionArgument', models.IntegerField(max_length=10)),
                ('nodeLongitude', models.IntegerField(max_length=10)),
                ('meanAnomaly', models.IntegerField(max_length=10)),
                ('absoluteMagnitude', models.IntegerField(max_length=10)),
                ('periphelionDistance', models.IntegerField(max_length=10)),
                ('estDiaInKm', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='classification',
            name='absoluteMagnitude',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='estDiaInFeetMax',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='estDiaInFeetMin',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='estDiaInKmMax',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='estDiaInKmMin',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='estDiaInMMax',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='estDiaInMMin',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='estDiaInMilesMax',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='estDiaInMilesMin',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='neoReferenceId',
            field=models.IntegerField(max_length=10),
        ),
    ]
