# Generated by Django 3.1.7 on 2021-04-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroidApi', '0004_auto_20210402_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbits',
            name='estDiaInKm',
            field=models.IntegerField(default=0),
        ),
    ]
