# Generated by Django 3.1.7 on 2021-04-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asteroidApi', '0005_orbits_estdiainkm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classification',
            new_name='Classifications',
        ),
    ]
